### PR TITLE
Migrate to Material UI v5

### PR DESCRIPTION
**Pull request by HenryLiangzy**
Refer to issue #184, migrate the library to material UI v5 for those projects using material v5.

The library required react-material-workspace-layout [update](https://github.com/UniversalDataTool/react-material-workspace-layout/pull/16#issue-1079332272) and material-survey [update](https://github.com/CollegeAI/material-survey/pull/31#issue-1079337312), I have submitted PR for both of the libraries. Due to the dependency issue, this merge should confirm after those two libraries are successfully reviewed and updated.

For the code, I have successfully tested both on the storybook and my material v5 project. If there is any issue please let me know.

### CODE REVIEW

**Comment by seveibar** [comment]
@HenryLiangzy can you format a la prettier to fix the tests?

**Comment by HenryLiangzy** [comment]
I did prettier for all the files mentioned in the testing result, but some of them I did not make any change during the migration, so wondering why they got the prettier warning, but the rest of the files I did fix it and should be ok to pass the test. If there is any issue please let me know, many thanks for your help

**Comment by seveibar** [comment]
Checking now!

**Comment by seveibar** [comment]
Still failing, my guess is the versions of prettier are mismatching- it's possible that the CI uses a newer version of prettier and we need to fix the github workflow.

**Comment by HenryLiangzy** [comment]
@seveibar I have done the prettier test locally and all are pass, I'm not sure which version is using on GitHub, any hints for that issue?

Screen Shot 2021-12-29 at 2 10 24 am

**Comment by seveibar** [comment]
The github workflow probably uses the latest version, so just doing a "yarn add prettier" should update the version in the project enough to get the prettier versions matching. Alternatively we can adjust the workflow to use the prettier version listed in the package.json

**Comment by seveibar** [comment]
Thanks for working with me on this one @HenryLiangzy !

**Comment by HenryLiangzy** [comment]
> The github workflow probably uses the latest version, so just doing a "yarn add prettier" should update the version in the project enough to get the prettier versions matching. Alternatively we can adjust the workflow to use the prettier version listed in the package.json

Yeah, you are right. Using the latest version of prettier did format those files and pass the GitHub workflow. Many thanks for your help.

**Comment by HenryLiangzy** [comment]
Hi @seveibar, is it possible for you to review this final version?

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
@HenryLiangzy THANK YOU!!!!

**Comment by seveibar** [comment]
@HenryLiangzy if you are able to, I've given maintenance permissions because I haven't been very active maintaining this project (as we can see here from the delay). You understand the project arch so you have my trust :)

**Comment by HenryLiangzy** [comment]
@seveibar Many thanks for your review. 

I could continuously update the project but might need your help with the code review. Though I migrated the library to v5, the core components you have a better understanding and I'm afraid that I modified some of the core components will cause the legacy issue.

**Pull request merged**
